# Generated by Django 5.0 on 2025-12-15 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('teacher', 'Teacher'), ('student', 'Student'), ('staff', 'Staff'), ('director', 'Director'), ('manager', 'Manager')], default='student', max_length=20),
        ),
    ]
