# Generated by Django 5.0 on 2025-12-09 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0002_alter_userprofile_passport_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='group',
            unique_together=set(),
        ),
    ]
